image: docker:latest
services:
    - docker:dind

stages:
    - build-publish

variables:
    TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:test

build:
    stage: build
    script:
        - export DOCKER_HOST=$DOCKER_PORT
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --pull -t $TEST_IMAGE .
        - docker push $TEST_IMAGE
    tags:
        - aws,docker